import { CatalogItem, JobSpec, McpConnection } from "./types";

export const mockServices: CatalogItem[] = [
  {
    id: "svc-research-01",
    title: "시장 분석 리포트",
    summary: "대형주/섹터 동향, 경쟁 구도, 매크로 이슈를 분석해 리포트를 제공합니다.",
    category: "Research",
    outputFormat: "PDF",
    agentPriceLamports: "5000000",
    createdAt: "2026-02-20T10:00:00Z",
    updatedAt: "2026-02-24T15:30:00Z",
  },
  {
    id: "svc-code-audit-01",
    title: "스마트컨트랙트 감사",
    summary: "Solana Anchor 프로그램의 보안 취약점을 점검하고 리포트를 제공합니다.",
    category: "Security",
    outputFormat: "Markdown",
    agentPriceLamports: "15000000",
    createdAt: "2026-02-18T09:00:00Z",
    updatedAt: "2026-02-25T08:00:00Z",
  },
  {
    id: "svc-data-01",
    title: "온체인 데이터 파이프라인",
    summary: "Solana 트랜잭션 데이터를 수집하고 대시보드로 제공합니다.",
    category: "Data",
    outputFormat: "CSV + Dashboard",
    agentPriceLamports: "8000000",
    createdAt: "2026-02-22T14:00:00Z",
    updatedAt: "2026-02-25T10:00:00Z",
  },
  {
    id: "svc-content-01",
    title: "기술 문서 작성",
    summary: "API 문서, 아키텍처 문서, 온보딩 가이드를 자동 생성합니다.",
    category: "Content",
    outputFormat: "Markdown",
    agentPriceLamports: "3000000",
    createdAt: "2026-02-21T11:00:00Z",
    updatedAt: "2026-02-24T16:00:00Z",
  },
];

export const mockJobs: JobSpec[] = [
  {
    key: "job-001",
    buyer: "7xKX...pQ3r",
    jobId: "1",
    serviceId: "svc-research-01",
    serviceTitle: "시장 분석 리포트",
    taskTitle: "2026 DePIN 시장 분석",
    taskBrief: "DePIN 섹터의 시장 규모와 주요 프로젝트를 분석",
    requestStatus: "approved",
    decisionReason: "기준 충족",
    decidedAt: "2026-02-24T12:00:00Z",
    submittedAt: null,
    lastSubmissionPreview: "",
    createdAt: "2026-02-23T10:00:00Z",
    updatedAt: "2026-02-24T12:00:00Z",
    onChainStatus: 1,
  },
  {
    key: "job-002",
    buyer: "7xKX...pQ3r",
    jobId: "2",
    serviceId: "svc-code-audit-01",
    serviceTitle: "스마트컨트랙트 감사",
    taskTitle: "OutcomeEscrow v2 보안 감사",
    taskBrief: "SPL 토큰 정산 로직의 취약점 검토",
    requestStatus: "approved",
    decisionReason: "",
    decidedAt: "2026-02-25T09:00:00Z",
    submittedAt: "2026-02-25T14:00:00Z",
    lastSubmissionPreview: "총 3건의 Medium 이슈 발견, 상세 내용 첨부",
    createdAt: "2026-02-24T08:00:00Z",
    updatedAt: "2026-02-25T14:00:00Z",
    onChainStatus: 2,
  },
  {
    key: "job-003",
    buyer: "9aBC...xY2z",
    jobId: "3",
    serviceId: "svc-data-01",
    serviceTitle: "온체인 데이터 파이프라인",
    taskTitle: "Jupiter DEX 거래량 분석",
    taskBrief: "최근 30일 Jupiter 거래량 및 주요 구간 분석",
    requestStatus: "pending",
    decisionReason: "",
    decidedAt: null,
    submittedAt: null,
    lastSubmissionPreview: "",
    createdAt: "2026-02-25T11:00:00Z",
    updatedAt: "2026-02-25T11:00:00Z",
    onChainStatus: 0,
  },
];

export const mockMcpConnections: McpConnection[] = [
  {
    name: "GPT-Research-Agent",
    serverUrl: "https://mcp.solheaven.io",
    healthPath: "/health",
    priceLamports: "1000000",
    priceDisplay: "1.0000 USDC",
    priceSymbol: "USDC",
    priceSol: "1.0000 USDC",
    hasAuthToken: true,
    lastStatus: "ok",
    lastCheckedAt: "2026-02-25T15:30:00Z",
    lastHttpStatus: 200,
    lastMessage: "mcp server reachable",
  },
  {
    name: "Market-Intel-MCP",
    serverUrl: "https://intel.solheaven.io",
    healthPath: "/v1/health",
    priceLamports: "2500000",
    priceDisplay: "2.5000 USDC",
    priceSymbol: "USDC",
    priceSol: "2.5000 USDC",
    hasAuthToken: true,
    lastStatus: "ok",
    lastCheckedAt: "2026-02-25T15:28:10Z",
    lastHttpStatus: 200,
    lastMessage: "mcp server reachable",
  },
  {
    name: "Onchain-Risk-Scanner",
    serverUrl: "https://risk.solheaven.io",
    healthPath: "/healthz",
    priceLamports: "4000000",
    priceDisplay: "4.0000 USDC",
    priceSymbol: "USDC",
    priceSol: "4.0000 USDC",
    hasAuthToken: false,
    lastStatus: "error",
    lastCheckedAt: "2026-02-25T15:26:03Z",
    lastHttpStatus: 503,
    lastMessage: "mcp server responded with 503",
  },
  {
    name: "Deep-Research-KR",
    serverUrl: "https://kr-research.solheaven.io",
    healthPath: "/health",
    priceLamports: "1800000",
    priceDisplay: "1.8000 USDC",
    priceSymbol: "USDC",
    priceSol: "1.8000 USDC",
    hasAuthToken: true,
    lastStatus: "ok",
    lastCheckedAt: "2026-02-25T15:23:20Z",
    lastHttpStatus: 200,
    lastMessage: "mcp server reachable",
  },
  {
    name: "FinNews-Summarizer",
    serverUrl: "https://news-mcp.solheaven.io",
    healthPath: "/v1/health",
    priceLamports: "1200000",
    priceDisplay: "1.2000 USDC",
    priceSymbol: "USDC",
    priceSol: "1.2000 USDC",
    hasAuthToken: false,
    lastStatus: "idle",
    lastCheckedAt: null,
    lastHttpStatus: null,
    lastMessage: "not connected",
  },
  {
    name: "Code-Audit-Agent",
    serverUrl: "https://audit.solheaven.io",
    healthPath: "/health",
    priceLamports: "3500000",
    priceDisplay: "3.5000 USDC",
    priceSymbol: "USDC",
    priceSol: "3.5000 USDC",
    hasAuthToken: true,
    lastStatus: "ok",
    lastCheckedAt: "2026-02-25T15:20:41Z",
    lastHttpStatus: 200,
    lastMessage: "mcp server reachable",
  },
  {
    name: "Data-Pipeline-MCP",
    serverUrl: "https://data-pipe.solheaven.io",
    healthPath: "/healthz",
    priceLamports: "2700000",
    priceDisplay: "2.7000 USDC",
    priceSymbol: "USDC",
    priceSol: "2.7000 USDC",
    hasAuthToken: true,
    lastStatus: "error",
    lastCheckedAt: "2026-02-25T15:18:05Z",
    lastHttpStatus: 504,
    lastMessage: "mcp server responded with 504",
  },
];

export const mockMcpConnection: McpConnection = mockMcpConnections[0];

export const mockWallets = {
  admin: "SoLH...Admin",
  ops: "SoLH...Ops42",
  buyer: "7xKX...pQ3r",
  operator: "4mNR...Op8s",
  treasury: "Tres...ury99",
};
